# Step 1: Build the ASP.NET Core application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Xichavelo.Web.csproj", "./"]
RUN dotnet restore "Xichavelo.Web.csproj"
COPY . .
RUN dotnet publish "Xichavelo.Web.csproj" -c Release -o /app/publish

# Step 2: Run the application in runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Xichavelo.Web.dll"]